### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by xman95** [capplex/dasprojekt#2]
Indításkor a következő hibaüzenetet küldi a program:

```
c:\Users\Ati>php quickstart.php
PHP Fatal error:  Uncaught LogicException: refresh token must be passed in or set as part of setAccessToken in C:\Users\Ati\vendor\google\apiclient\src\Google\Client.php:258
Stack trace:
#0 C:\Users\Ati\quickstart.php(54): Google_Client->fetchAccessTokenWithRefreshToken(NULL)
#1 C:\Users\Ati\quickstart.php(74): getClient()
#2 {main}
  thrown in C:\Users\Ati\vendor\google\apiclient\src\Google\Client.php on line 258
```

**Comment by capplex** [comment]
`C:\Users\<Felhasználónév>\.credentials` mappában lévő `sheets.googleapis.com-php-quickstart.json` fájlt törölni kell. 
Ezután újra hitelesíteni kell...
A program valamiért nem kér új token-t ha az előző lejárt.
